### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by jeroenptrs** [nos/visual-identity#1]
* [x] A user should be able to open/close the sidebar. (Collapsible sidebar)
* [x] The sidebar is sort of an "app" bar, where bookmarks to dApps are stored. Clicking these icons will open them in a new tab.
* [x] Need to experiment with the standard sidebar color, it should be way more neutral and dApps can set it themselves when you're on their page
* [x] Bottom icon is logout (not notifications)
* [ ] Explore thinner desktop sidebar versions

### Mobile / Tablet
* [ ] Is a sidebar possible/necessary on mobile? Maybe as a swipeable interaction

**Comment by fabric-8** [comment]
## Sidebar V1

#### 👉 [Sidebar Styleguide (WIP)](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=203%3A60)
#### 👉 [Check the Clickable prototype on Figma for Expand/Collapse](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=195%3A415&scaling=scale-down)

### Todo for V2
- Add bookmarks
- Mobile version

**Comment by fabric-8** [comment]
## Sidebar V2

#### 👉 [Sidebar Styleguide (WIP)](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=203%3A60)
#### 👉 [Check the Clickable prototype on Figma for Expand/Collapse](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=195%3A415&scaling=scale-down)

### Changelog
- Added bookmarks concept

### Todo for V3
- Mobile version
- Explore thinner desktop sidebar versions

**Comment by jeroenptrs** [comment]
@fabric-8 in addition to the above mentioned changes, could you experiment with making the sidebar thinner? Station has a very thin sidebar but is still very keen on usability. I have the impression that (especially on lower dimensions) the sidebar is several amounts too thick.

**Comment by fabric-8** [comment]
@jeroenptrs A bit worried about that one – The min-width of the sidebar is pretty much dictated by the osx window icons (I know, they're on the right on windows which means we won't have that issue there, but if we want to make it look similar on both platforms the issue persists…).

Right now I'm adhering to the system default, so going narrower while keeping those doesn't seem to be an option. If we do want to go narrower we have to add the default app bar on mac os which ain't that nice as well. 

I can add another exploration for this so you guys see options + differences across win+macOS
