### ISSUE TITLE
Address bar

### ISSUE THREAD

**Issue by jeroenptrs** [nos/visual-identity#2]
The address bar should not only be the place where a user enters the address to navigate to a new dApp, it's also the place for dApp related info:
* [x] If it's registered on the official name service contract (sort of like the `secure`/`https` address bar tag in Chrome/Firefox
* [x] `add to sidebar` button (as shown in the winner's design)
* [x] Should be thinner as compared to the original design (take a look at Chrome)

## Mobile / Tablet
* [ ] How do mobile browsers do this?
* [ ] Does the address bar persist when scrolling?
* [ ] Does the add to sidebar button remain in the address bar or does it get externalized?

**Comment by fabric-8** [comment]
## Address Bar V1

#### 👉 [Check the Clickable prototype on Figma](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=97%3A439&scaling=scale-down)  👈

![dapp](https://user-images.githubusercontent.com/4112698/41689281-25e8a278-74f0-11e8-9e39-020f38a7fddc.png)


### Changelog
- url bar now slimmer, thinner and meaner 👹
- Updated bookmark icon
- Removed social share (for now)
- Replace `Secure` with the `nos:// protocol`, and then have the domain itself separated from the protocol
- Keep bookmark icon green (but transparent) after it's clicked so you can tell it's bookmarked by the color

### Todo's for V2
- Mobile Views
