### ISSUE TITLE
Browser controls

### ISSUE THREAD

**Issue by jeroenptrs** [nos/visual-identity#4]
* [x] Refreshing the dAppContainer
* [x] Next / Previous in the navigation history
* [x] Notifications (not specifically a control, but an option that is in the same window space as the controls)

## Mobile / Tablet
* [ ] Where are they located on the mobile layout in comparison to desktop?
* [ ] Are there possible gestures (f.e. swipe down to refresh) that we can incorporate in a visual manner?

**Comment by fabric-8** [comment]
## Browser Controls V1

#### 👉 [Check the Clickable prototype on Figma](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=70%3A3&scaling=scale-down)  👈

![browser controls - sidebar expanded](https://user-images.githubusercontent.com/4112698/41679480-a30d9d02-74ce-11e8-8ff0-2a8dcd369518.png)
![browser controls - sidebar collapsed](https://user-images.githubusercontent.com/4112698/41679481-a3288fae-74ce-11e8-8adc-eb1bf2b38d5e.png)

### Changelog
- Added sidebar collapse controls to top bar
- Added notification (+ pending notifications indicator)
- Removed "old bookmarks expand"
- Updated url-bar (Thanks for adding the secure label @iammtong !)
- Updated color scheme: Based on @deanpress feedback I made the greys "less tinted", hence neutralising the palette a bit without making it flat (& boring 😛) greyscale. Changes already quite visible here

### Todo's for V2
- Mobile Views

Happy to hear your feedback!

**Comment by fabric-8** [comment]
## Browser Controls V2

#### 👉 [Check the Clickable prototype on Figma](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=70%3A3&scaling=scale-down)  👈

![sidebar collapsed](https://user-images.githubusercontent.com/4112698/42082634-cd5f93a6-7b88-11e8-8aee-110633b6ef49.png)

![sidebar expanded](https://user-images.githubusercontent.com/4112698/42082633-cd44819c-7b88-11e8-81a6-3ce97f22ef58.png)

### Changelog
- Added Control Bar to the [styleguide](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=194%3A31311)
- Multiple Tabs + states (Check on [styleguide](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=194%3A31311))
- New sidebar collapse icon
- Favicons
- Icon States (Check on [styleguide](https://www.figma.com/file/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=194%3A31311))

## Todo's for V3
- Mobile Views

Happy to hear your feedback!

**Comment by fabric-8** [comment]
## Browser Controls V2.1

#### 👉 [Check the Clickable prototype on Figma](https://www.figma.com/proto/apqKpVZZDzppAb0lVH69iiZn/nOS-Client?node-id=70%3A3&scaling=scale-down)  👈

### Changelog
- New sidebar expand/collapse icon
- Additional tab styling details: 2 inactive tabs next to each other, close tab hover fx

## Todo's for V3
- Mobile Views

Happy to hear your feedback!
